FALCO ANSIBLE (STANDALONE)

---
- name: Install and Configure Falco on Standalone Machines
  hosts: standalone
  become: yes
  vars:
    wazuh_manager_ip: "192.168.x.x"  # Replace with your Wazuh Manager IP

  tasks:
    - name: Install Falco
      apt:
        name: falco
        state: present

    - name: Configure Falco to send logs to Wazuh (Syslog)
      copy:
        dest: /etc/falco/falco.yaml
        content: |
          syslog:
            enabled: true
            host: "{{ wazuh_manager_ip }}"
            port: 514

    - name: Restart Falco service
      systemd:
        name: falco
        state: restarted

    - name: Configure Wazuh to read Falco logs
      copy:
        dest: /var/ossec/etc/ossec.conf
        content: |
          <ossec_config>
            <localfile>
              <log_format>syslog</log_format>
              <location>/var/log/falco_alerts.log</location>
            </localfile>
          </ossec_config>
      notify:
        - Restart Wazuh Agent

  handlers:
    - name: Restart Wazuh Agent
      systemd:
        name: wazuh-agent
        state: restarted