##
# Configure auditd on the target system.
#
# 
# Initially written by a Tired Matthew Harper
##

---
- name: Auditd-Configuration
  hosts: infra # Need to Coordinate This
  become: true # Need to be sudo
  vars:
    conf_file_trgt: /etc/audit/rules.d/ccdc.rules
    conf_name: ./Configs/audit_rules.conf # Change to something else if wanted
  tasks:
    - name: Configure-auditd
      ansible.builtin.copy:
        src: "{{ conf_name }}"
        dest: "{{ conf_file_trgt }}"
        remote_src: false
        owner: root
        group: root
        mode: '644'
    - name: Load-Config
      ansible.builtin.systemd:
        name: auditd
        state: restarted
      ignore_errors: yes
