##
# Usage: Execute a given script on the target system
#
# Initially written by a Tired Matthew Harper
##

---
- name: Run-Files
  hosts: infra # Need to Coordinate This
  become: true # Need to be sudo
  vars:
    script:
      - ./SourceDir/test.sh
  tasks:
    - name: Script-Runner
      script: "{{ item }}"
      ignore_errors: true
      with_items: "{{ script }}"
